services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: Rushikesh@1
            MYSQL_DATABASE: reservation
            MYSQL_USER: rushikesh
            MYSQL_PASSWORD: Rushikesh@1
        ports:
            - "3306:3306"
        networks:
            - flightservice-network
        volumes:
            - mysql_data:/var/lib/mysql
    springboot-app:
        image: rushikesh0028/flightservice:v1.0
        ports:
            - "8080:8080"
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: rushikesh
            DB_PASSWORD: Rushikesh@1
        networks:
            - flightservice-network
        volumes:
            - ./app/logs:/logs
    elasticsearch:
        image: elasticsearch:8.16.1
        # @ignore for swarm
        # restart: always
        environment:
          - discovery.type=single-node
          - ES_JAVA_OPTS=-Xms512m -Xmx512m
          - ELASTIC_PASSWORD=changeme  # Initial password for the 'elastic' superuser
        networks:
          - flightservice-network
        ports:
          - "9200:9200"
          - "9300:9300"
        volumes:
          - es_data:/usr/share/elasticsearch/data/
    kibana-token-generator:
        image: curlimages/curl:latest
        user: root 
        depends_on:
          - elasticsearch
        networks:
          - flightservice-network
        entrypoint: ["sh", /tokenGenerator.sh]
        volumes:
          - ./kibana_token:/token
          - ./tokenGenerator.sh:/tokenGenerator.sh
        # @ignore for docker-compose
        deploy:
            restart_policy:
                condition: none
    logstash:
        image: logstash:8.16.1
        # @ignore for swarm
        restart: always
        volumes:
            - ./logstash.conf:/logstash.conf
            - ./app/logs:/app/logs
        command: logstash -f /logstash.conf
        networks:
            - flightservice-network
        depends_on:
            - elasticsearch
        ports:
            - '9600:9600'
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    kibana:
        image: kibana:8.16.1
        # @ignore for swarm
        # restart: always
        depends_on:
        # @ignore for swarm
          # kibana-token-generator:
          #   condition: service_completed_successfully #Works only in docker-compose
        # @ignore for docker-compose
            - kibana-token-generator
            - elasticsearch
        networks:
          - flightservice-network
        ports:
          - "5601:5601"
        entrypoint: ["sh", /kibanaInit.sh]
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        volumes:
          - ./kibana.yml:/usr/share/kibana/config/kibana.yml:Z
          - ./kibana_token:/token
          - ./kibanaInit.sh:/kibanaInit.sh
networks:
    flightservice-network:
        external: true
volumes:
    mysql_data:
    es_data:
