flightservice:
  image: rushikesh0028/flightservice:v1.0
  replicas: 2
  resources:
    requests:
      cpu: "800m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "256Mi"
  env:
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_USER: "rushikesh"
    DB_PASSWORD: "Rushikesh@1"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

